### ISSUE TITLE
Not 300b?

### ISSUE THREAD

**Issue by soswow** [Kelin2025/nanoclone#11]
https://bundlephobia.com/result?p=nanoclone@0.2.1 says it's 450 minified-gzipped

**Comment by Kelin2025** [comment]
Clone this repo and run `npm run size`  
Still **under 300b** even with Map&Set support being added a while ago
![image](https://user-images.githubusercontent.com/4208480/199111631-e0c66555-3007-4203-b519-18041db8a5cd.png)
