### ISSUE TITLE
Use Map instead of Array for `circulars`

### ISSUE THREAD

**Issue by broofa** [Kelin2025/nanoclone#13]
[This code](https://github.com/Kelin2025/nanoclone/blob/master/src/index.js#L55-L57) seems like a significant perf issue.  A linear searches of array won't scale well.  Consider using a `Map` instead?

(Apologies if this a bad suggestion for some reason.  I was just quickly perusing the code and this stood out as a seemingly-obvious perf improvement.)

**Comment by Kelin2025** [comment]
Hi!
The reason of Map's refusal was that this code was written like 4 years ago, when Map didn't have good browser support (and I don't use any polyfills here in order to keep it nano) 
Will check browser support when wake up and probably use Map here

**Comment by broofa** [comment]
Map is supported for everything except IE these days.  I've attached a PR that uses Map.  It yields modest performance gains, but also fixes a couple other semi-serious issues.  Maybe do a major-version bump and drop IE support for the new version?
