### ISSUE TITLE
Use ES5

### ISSUE THREAD

**Issue by ai** [Kelin2025/nanoclone#2]
You use ES6 only for `const` and `export default`. You can simplify your build tools and reduce bundle size by using ES5. Just move `src/index.js` to `index.js` and then you can forget about Rollup and `dist/`.

**Comment by mrdimidium** [comment]
The refusal of the Assembly will simplify the testing process

**Comment by Kelin2025** [comment]
I removed **rollup** and **babel** in last commits. Also replaced `export default` to `module.exports`, `const` to `var` and `Object.keys()` to `for...in`
Thank you so much!
